### ISSUE TITLE
floating button

### ISSUE THREAD

**Issue by Kevinvaddoriya** [Kevinvaddoriya/RecycleContact#1]
in floating button add icon color is black but i want white . fix it
![Screenshot 2023-01-24 132855](https://user-images.githubusercontent.com/109676063/214239779-3947aed8-bad4-4520-b08d-9b409febee7f.png)

**Comment by Kevinvaddoriya** [comment]
![Screenshot 2023-01-24 132948](https://user-images.githubusercontent.com/109676063/214239872-ee36f649-56c8-4a38-b397-44a7ed78db97.png)
Do add icon white

**Comment by ghost** [comment]
Add this line on xml file.
app:tint="#fff"

**Comment by kevinvaddoriya1** [comment]
Change android:tint to app:android

**Comment by ghost** [comment]
Add this line on xml file.
app:tint="#fff"
